CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS chats (
    id SERIAL PRIMARY KEY,
    ext_id UUID NOT NULL DEFAULT uuid_generate_v4() UNIQUE,
    title VARCHAR(255) NOT NULL,
    last_message TEXT,
    created_by INTEGER NOT NULL REFERENCES users(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
