services:
  go_db:
    image: postgres:17
    container_name: go_db
    ports:
      - "5764:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "857:8080"
    depends_on:
      - go_db